name: upm sync package
on:
  workflow_call:
jobs:
  setup:
    runs-on: ubuntu-slim
    outputs:
      versions: ${{ steps.archive.outputs.versions }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: package
      - uses: actions/checkout@v6
        with:
          repository: RageAgainstThePixel/workflows
          ref: main
          path: workflows
      - name: get version(s)
        id: archive
        run: ../workflows/.github/workflows/scripts/google-package-fetch-versions.sh
        working-directory: package
  sync:
    needs: setup
    runs-on: ubuntu-slim
    permissions:
      contents: write
    if: ${{ needs.setup.outputs.versions != '[]' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        version: ${{ fromJson(needs.setup.outputs.versions) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
          path: package
      - uses: actions/checkout@v6
        with:
          repository: RageAgainstThePixel/workflows
          ref: main
          path: workflows
      - name: sync package@${{ matrix.version }}
        run: ../workflows/.github/workflows/scripts/google-package-sync-upm-package.sh
        working-directory: package
        env:
          MATRIX_VERSION: ${{ matrix.version }}
